Build system update
comp compall and lked are now much closer to the originals and
Makefile.in has been updated accordingly.
No new features are provided.

diff --git a/comp b/comp
--- a/comp
+++ b/comp
@@ -42,8 +42,7 @@ if (!($?GMS_BG_MODEL)) set GMS_BG_MODEL=' '
 #
 #    ---- and now the script begins...
 #
-#unset echo
-set FAILED=0
+unset echo
 set MODULE=$1
 set ACTONLY=$2   # this argument is almost always omitted
 if (null$MODULE == null) then
@@ -51,8 +50,8 @@ if (null$MODULE == null) then
    exit
 endif
 #
-#echo ======================== $MODULE ==============================
-#date
+echo ======================== $MODULE ==============================
+date
 #
 #   Let's be sure they typed the intended target correctly
 #
@@ -433,7 +432,7 @@ if (($BLAS3 == true) && ($MODULE == mthlib)) goto act
 #
 #   All other modules are straight FORTRAN, just copy them.
 #
-#echo Copying source code, $MODULE.src does not require activation.
+echo Copying source code, $MODULE.src does not require activation.
 cp $SRCDIR/$MODULE.src $MODULE.f
 goto cmp
 #
@@ -608,7 +607,7 @@ endif
 #   extra support included in the activation program (e.g. DDOT to SDOT
 #   conversion, or exponent D to E changing), so 'sed' suffices.
 #
-#echo "Activating $TARGET lines in $SRCDIR/$MODULE.src to produce $MODULE.f..."
+echo "Activating $SRCDIR/$MODULE.src to create $MODULE.f for target $TARGET..."
 #
 setenv   SRCIN $SRCDIR/$MODULE.src
 setenv CODEOUT $MODULE.f
@@ -898,6 +897,7 @@ cmp:
 #   syntax scan by the nifty FORTRAN analysis program FTNCHEK.
 #
 if ($ACTONLY == true) then
+#AAD since we operate within OBJDIR, the following is not required
    #mv -f $MODULE.f ~/scr
    exit
 endif
@@ -945,7 +945,6 @@ if ($TARGET == axp64) then
    if ($MODULE == zheev) set OPT='-O0'
    set echo
    $FORT -c -i8 -v -automatic -col72 $OPT $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -975,7 +974,6 @@ if ($TARGET == cray-pvp) then
    if ($MODULE == zheev)  set OPT='-O0'    # defensive compiling
    set echo
    f90 -c -V $OPT $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -992,7 +990,6 @@ if ($TARGET == cray-t3e) then
    if ($MODULE == zheev) set OPT='-O0'   # defensive compiling
    set echo
    env TARGET=cray-t3e f90 -c $OPT -dp -Onomsgs,nonegmsgs $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1017,7 +1014,6 @@ if ($TARGET == cray-x1) then
    if ($MODULE == zheev)  set OPT='-O0'   # defensive compiling
    set echo
    ftn -c -V $OPT $LST -Ossp,aggress -xomp -dp -sdefault64 $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1066,7 +1062,6 @@ if ($TARGET == cray-xd1) then
 
    set echo 
    $USE_FTN -c $OPT -Mnosecond_underscore -tp $AMD_TRGT -i8 $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1217,7 +1212,6 @@ if ($TARGET == fuji-pp32) then
    set OPT = '-Kfast_GP2=3,prefetch=5'
    set echo
    f90 -c -fs $OPT $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 
@@ -1229,7 +1223,6 @@ if ($TARGET == fuji-pp64) then
    if ($MODULE == gamess) set OPT='-O0'  # only fails in 64 bit mode
    set echo
    f90 -c -fs $OPT -KV9 -CcdII8  $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1273,7 +1266,6 @@ if ($TARGET == hpux32) then
    if ($MODULE == zheev)  set OPT='+O0'   # defensive compiling
    set echo
    f90 -c $OPT +nosave +noppu $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1294,7 +1286,6 @@ if ($TARGET == hpux64) then
    if ($MODULE == zheev)  set OPT='+O0'   # defensive compiling
    set echo
    f90 -c $OPT +DD64 +i8 +nosave +noppu $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1380,9 +1371,7 @@ if (($TARGET == ibm32) || ($TARGET == ibm64) || ($TARGET == ibm64-sp)) then
 #
    set echo
    $FORT -c $OPT $BITS -qarch=$ARCH -qtune=$TUNE \
-         -qsuppress=cmpmsg \
          -qflag=W:W -qhalt=W -qspillsize=2500 -qnosave $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1401,31 +1390,13 @@ if ($TARGET == ibm-bg) then
       set ARCH='450d'
       set TUNE='450'
    endif
-   set OPT='-O3'
-   if ($MODULE == grd2b)  set OPT='-O3 -qspillsize=1500'
-   if ($MODULE == gugdm)  set OPT='-O2'
-   if ($MODULE == gugem)  set OPT='-O2'
-   if ($MODULE == qrel)   set OPT='-O2'
-   if ($MODULE == trnstn) set OPT='-O2'
-   if ($MODULE == ormas1) set OPT='-O2'
+   set OPT='-O2 -qstrict'
+   if ($MODULE == grd2b)  set OPT='-O2 -qstrict -qspillsize=1500'
    if ($MODULE == prpel)  set OPT='-O0'  # Graham, 2010, for the P
-   if ($MODULE == zheev)  set OPT='-O0'
-   if ($MODULE == qeigen) set OPT="-O3 -qstrict"
-   if ($MODULE == fmoint) set OPT="-O3 -qstrict"
-#        higher optimization for selected modules
-   if ($MODULE == scflib) set OPT="-O3 -qhot"
-   if ($MODULE == int2a)  set OPT="-O3 -qhot"
-   if ($MODULE == int2b)  set OPT="-O3 -qhot"
-   if ($MODULE == int2r)  set OPT="-O3 -qhot"
-   if ($MODULE == grd2a)  set OPT="-O3 -qhot"
-   if ($MODULE == grd2b)  set OPT="-O3 -qhot"
-   if ($MODULE == grd2c)  set OPT="-O3 -qhot"
-   if ($MODULE == mp2ddi) set OPT="-O3 -qhot"
-   if ($MODULE == rhfuhf) set OPT="-O3 -qhot"
+   if ($MODULE == zheev)  set OPT='-O0'  # the usual "defensive compiling"
    set echo
    $FORT -c $OPT -qarch=$ARCH -qtune=$TUNE \
          -qflag=W:W -qhalt=W -qmaxmem=-1  -qnosave $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1475,7 +1446,6 @@ if ($TARGET == linux32) then
    set echo
    g77 -c $OPT -malign-double -fautomatic \
            -Wno-globals -fno-globals $MODULE.f
-   set FAILED=$status
    unset echo
    breaksw
 #
@@ -1499,7 +1469,6 @@ if ($TARGET == linux32) then
    endif
    set echo
    gfortran -c $OPT -std=legacy $MODULE.f
-   set FAILED=$status
    unset echo
    breaksw
 #
@@ -1525,7 +1494,6 @@ if ($TARGET == linux32) then
    if ($GMS_IFORT_VERNO >= 12) set EXTRAOPT="$EXTRAOPT -warn nousage"
    set echo
    ifort -c -i4 $OPT -ftz -auto $EXTRAOPT $MODULE.f
-   set FAILED=$status
    unset echo
    breaksw
 #
@@ -1556,7 +1524,6 @@ if ($TARGET == linux32) then
    if ($MODULE == bassto) set OPT = '-O0'  # Takako
    set echo
    pgf77 -c $OPT -Msecond_underscore $MODULE.f
-   set FAILED=$status
    unset echo
    breaksw
 #
@@ -1634,6 +1601,7 @@ if ($TARGET == linux64) then
 #           -finit-real=<zero|inf|-inf|nan>  could be interesting debug opt
 #           -fno-automatic forces static storage of all local variables
       set OPT='-O2'
+      if (".$GMS_DEBUG_FLAGS" != .) set OPT="$GMS_DEBUG_FLAGS"
       if ($MODULE == zheev)  set OPT='-O0'  # defensive compiling
       if (($MODULE == qeigen) || ($MODULE == int2c)) then
          mv -f $MODULE.f $MODULE.junk
@@ -1644,7 +1612,6 @@ if ($TARGET == linux64) then
       endif
       set echo
       gfortran -c -fdefault-integer-8 $OPT -std=legacy $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
 
@@ -1688,7 +1655,6 @@ if ($TARGET == linux64) then
       if ($GMS_IFORT_VERNO >= 12) set EXTRAOPT="$EXTRAOPT -warn nousage"
       set echo
       ifort -c -i8 $OPT -ftz -auto $EXTRAOPT $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
 
@@ -1711,7 +1677,6 @@ if ($TARGET == linux64) then
       if ($MODULE == zheev)  set OPT = '-Mprof=func -O0' # defensive compiling
       set echo
       pgf77 -c -i8 -i8storage -mcmodel=medium $OPT $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
 #
@@ -1730,7 +1695,6 @@ if ($TARGET == linux64) then
       if ($MODULE == zheev)  set OPT='-O0'
       set echo
       pathf90 -c -r8 -i8 $OPT $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
 #
@@ -1800,7 +1764,6 @@ if ($TARGET == mac32) then
       endif
       set echo
       g77 -c $OPT -fautomatic -Wno-globals -fno-globals $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
    case gfortran:
@@ -1815,7 +1778,6 @@ if ($TARGET == mac32) then
       endif
       set echo
       gfortran -c $OPT -std=legacy $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
    default:
@@ -1827,6 +1789,9 @@ endif
 #
 if ($TARGET == mac64) then
    set OPT='-O2'
+   if (`gcc -dumpversion` =~ 4\.6\.[0-9]*) then
+      if (($MODULE == tddgrd) set OPT='-O0'   # this issue seen in 4.6.1
+   endif
    if ($MODULE == zheev)  set OPT='-O0'  # defensive compiling
    if (($MODULE == qeigen) || ($MODULE == int2c)) then
       mv -f $MODULE.f $MODULE.junk
@@ -1837,7 +1802,6 @@ if ($TARGET == mac64) then
    endif
    set echo
    gfortran -c -m64 -fdefault-integer-8 $OPT -std=legacy $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1866,7 +1830,6 @@ if ($TARGET == necsx) then
 #
    set echo
    f90 -c -ebw -size_t64 $OPT $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -1901,7 +1864,6 @@ if (($TARGET == sgi32) || ($TARGET == sgi64)) then
    set FLAGS='-automatic -G0 -woff 2290 -OPT:Olimit=0'
    set echo
    $FORT -c $OPT $INTS $FLAGS $MODULE.f
-   set FAILED=$status
    unset echo
 endif
 #
@@ -2023,7 +1985,6 @@ if (($TARGET == sun32) || ($TARGET == sun64)) then
       set WARN='-erroff=WARNING_1278,WARNING_1279,WARNING_1615'
       set echo
       f90 -c -stackvar -xtypemap=integer:$BITS $OPT $WARN $ARCH $MODULE.f
-      set FAILED=$status
       unset echo
    else
 #
@@ -2041,7 +2002,6 @@ if (($TARGET == sun32) || ($TARGET == sun64)) then
       if ($MODULE == zheev)  set OPT='-O0'
       set echo
       f77 -c $OPT -stackvar $MODULE.f
-      set FAILED=$status
       unset echo
    endif
 endif
@@ -2101,7 +2061,6 @@ if ($TARGET == win32) then
    set echo
    pgf77 -c -Msecond_underscore -Munix -Bstatic $OPT $GMS_WIN_TP \
          -o $MODULE.o $MODULE.f
-   set FAILED=$status
    unset echo
    breaksw
 #
@@ -2157,7 +2116,6 @@ if ($TARGET == win64) then
 #
       set echo
       pgf77 -c -i8 -Bstatic $OPT $GMS_WIN_TP -o $MODULE.o $MODULE.f
-      set FAILED=$status
       unset echo
       breaksw
 #
@@ -2171,11 +2129,28 @@ endif
 #
 #  Store the generated object code, clean up, and quit
 #
+#AAD since we operate within OBJDIR, the following is not required
 #mv -f $MODULE.o $OBJDIR/$MODULE.o
 if ($TINKCODE == yes) exit
-#rm -f $MODULE.f
-if ($SRCDIR == .) rm -f $MODULE.src    # delete copy with no scalar code
-#unset echo
-#date
-#time
-exit $FAILED
+#
+#  option to possibly save the preprocessed code, out of the way
+#AAD preprocessed code is always saved for use with FTNCHEK
+#
+#if ( ".$GMS_DEBUG_FLAGS" == '.' ) then
+#   rm -f $MODULE.f
+#else
+#   mv -f $MODULE.f tmp/
+#endif
+#if ($SRCDIR == .) rm -f $MODULE.src    # delete copy with no scalar code
+#
+#  Exit gracelessly if we fail to generate the object file
+#
+unset echo
+date
+time
+if (-e $MODULE.o ) then
+   exit
+else
+   echo Compilation failure for $MODULE, please fix the problem.
+   exit 1
+endif
