Windows build support for 'pgfortran' for F90 source cpmchf.src
The file cpmchf.src is an F90 file that can not be compiled with 'pgf77'.
This push fixes the problem by adding 'pgfortran' support (an F90/F95 compiler).

PGI+MKL support was also added.

There are no changes to the GAMESS source only the build files.  However, testing
was done on exalted of the modifications listed below:  EXAM43 fails.

However, similar testing was done with an unmodified ORIGIN and EXAM43 still failed.

So, EXAM43 was failing prior to this PUSH.

Change-Id: I2943bbb9fdd071e03d482203f4ac777c907fefb0

diff --git a/config b/config
--- a/config
+++ b/config
@@ -896,7 +896,6 @@ breaksw
 #
 case win32:
 case win64:
-
 #      GMS_WIN_OPT   will be set below, to user's optimization level
 #      GMS_WIN_FLAGS adds extra flags for purposes of testing,
 #                    but will be set to a null string,
@@ -911,14 +910,36 @@ if ($?TP) then
 else
    setenv GMS_WIN_TP "''"
 endif
-
 badwinfortran:
 tput clear
+echo "/============================================================================\"
+echo "|        AVAILABLE OPTIONS UNDER MICROSOFT WINDOWS OPERATING SYSTEMS         |"
+echo "|============================================================================|"
+echo "| Compiler  | Math Library | 32-bit | 64-bit |            Comments           |"
+echo "|============================================================================|"
+echo "|           | NONE         |  YES   |  YES   | Fortran 95 compiler. Use pgf77|"
+echo "| pgfortran |--------------------------------| for source that may not be F95|"
+echo "|           | PGI BLAS     |  YES   |  YES   | compatible.                   |"
+echo "| ---------------------------------------------------------------------------|"
+echo "|           | NONE         |  YES   |  YES   |                               |"
+echo "|           |----------------------------------------------------------------|"
+echo "|           | PGI BLAS     |  YES   |  YES   |                               |"
+echo "| pgf77     |----------------------------------------------------------------|"
+echo "|           | ACML         |  YES   |  YES   |                               |"
+echo "|           |----------------------------------------------------------------|"
+echo "|           | MKL          |  YES   |  YES   |                               |"
+echo "| ---------------------------------------------------------------------------|"
+echo "|           | NONE         |   NO   |  YES   |                               |"
+echo "| ifort     |----------------------------------------------------------------|"
+echo "|           | MKL          |   NO   |  YES   |                               |"
+echo "\============================================================================/"
+echo " "
 echo "Windows Fortran Compiler"
 echo "------------------------"
 echo " "
-echo "'pgf77' - Portland Group Fortran 77 compiler (PGI)"
-echo "'ifort' - Intel Fortran compiler (Intel)"
+echo "'pgfortran' - Portland Group Fortran 95 compiler (PGI)"
+echo "'pgf77'     - Portland Group Fortran 77 compiler (PGI)"
+echo "'ifort'     - Intel Fortran compiler (Intel)"
 echo " "
 echo -n "Enter your Fortran compiler choice: "
 set GMS_FORTRAN=$<
@@ -935,6 +956,17 @@ switch ($GMS_FORTRAN)
       echo "Please enter only the main version number, such as 8, 9, 10, 11, 12"
       echo -n "Version? "
       set GMS_IFORT_VERNO=$<
+      breaksw
+   case pgfortran:
+      echo " "
+      echo "'pgfortran' - does not support quadruple precision, so heavy "
+      echo "              element DK3 resolution of the identity will fail"
+      echo "              but everything else should work."
+      echo " "
+      echo "This compiler is not commonly used with GAMESS, so"
+      echo "please be careful verifying the test examples all work."
+      echo "pgfortran will use target=$GMS_TARGET."
+      echo " "
       breaksw
    case pgf77:
       echo " "
@@ -996,15 +1028,17 @@ switch ($GMS_WIN_OPT)
   case fast:
     echo " "
     echo "'fast'     - will result in a GAMESS build that has not be tested for accuracy."
-	echo " ifort     - applies: -O3 -Qipo -Qprec-div- -QxHost"
-	echo " pgf77     - applies: -fast -Mipa=fast,safe"
+    echo " ifort     - applies: -O3 -Qipo -Qprec-div- -QxHost"
+    echo " pgfortran - applies: -fast -Mipa=fast,safe"
+    echo " pgf77     - applies: -fast -Mipa=fast,safe"
     echo " "
     echo "The linking step will take a while."
     echo " "
     breaksw
   case testing:
     echo " "
-    echo "'testing'"
+    echo "'testing'  - add compiler flags to the GMS_WIN_TP variable in quotes to the"
+    echo "             install.info file produced."
     echo " "
     breaksw
   default:
@@ -1027,17 +1061,26 @@ tput clear
 echo "Windows Math Library Selection"
 echo "-------------------------------"
 echo " "
-echo "'mkl' to Intel's math library (recommended if using ifort)"
 echo "'blas' to use PGI Compiler's BLAS library"
 echo "'acml' to use AMD's ACML BLAS library"
+echo "'mkl'  to Intel's math library"
 echo "'none' to use GAMESS's BLAS routine (much slower)"
 echo " "
 echo -n "Enter your math library choice: "
 set GMS_MATHLIB=$<
 #
 switch ($GMS_MATHLIB)
+   case blas:
+      echo "$GMS_FORTRAN compiler's BLAS library will be used"
+      echo " "
+      breaksw
+   case acml:
+      echo "ACML math library will be used. $GMS_FORTRAN will use the"
+      echo "'-Bdynamic -Macml' flags during linking."
+      echo " "
+      breaksw
    case mkl:
-      set GMS_MATHLIB_PATH='C:\Program Files (x86)\Intel\ComposerXE-2011\mkl\lib\intel64'
+      set GMS_MATHLIB_PATH='C:\Program Files (x86)\Intel\Composer XE 2011 SP1\mkl\lib\intel64'
       echo "The standard MKL installation is typically in:"
       echo "    $GMS_MATHLIB_PATH"
       echo "Normally the Intel compiler is automatically able to find the MKL library"
@@ -1074,7 +1117,7 @@ switch ($GMS_MATHLIB)
       breaksw
 endsw
 #
-if ($GMS_FORTRAN == pgf77) then
+if (($GMS_FORTRAN == pgf77) || ($GMS_FORTRAN == pgfortran)) then
   echo -n "Please hit <return> to continue to the target platform setup."
   set reply=$<
   tput clear
@@ -1382,7 +1425,6 @@ if ($GMS_TARGET == linux64) then
 endif
 
 if (($GMS_TARGET == win32) || ($GMS_TARGET == win64)) then
-  if (($GMS_FORTRAN == pgf77) || ($GMS_FORTRAN == ifort)) then
     echo " "
     echo -n "please hit <return> to to set up your network."
     set reply=$<
@@ -1424,9 +1466,7 @@ if (($GMS_TARGET == win32) || ($GMS_TARGET == win64)) then
         goto windows_mpi_selection
         breaksw
     endsw
-  endif
 endif
-
 #
 done_with_comm_choice:
 #
@@ -1466,7 +1506,7 @@ echo "setenv GMS_WIN_TP          $GMS_WIN_TP"         >> $cf
 echo "#         mathematical library setup"           >> $cf
 echo "setenv GMS_MATHLIB         $GMS_MATHLIB"        >> $cf
 if (($GMS_TARGET == win32) || ($GMS_TARGET  == win64) \
-                           && ($GMS_FORTRAN == ifort)) then
+                           && ($GMS_MATHLIB == mkl)) then
     if (null"$GMS_MATHLIB_PATH" != null) \
       echo 'setenv GMS_MATHLIB_PATH    "'"$GMS_MATHLIB_PATH"'"'   >> $cf
 else    
