finalize version 131
script, code, and DDI changes discovered while compiling
on 12 different platforms, including one LIBCCHEM build.

Change-Id: Ieb2e9ad4435399ddfa4d6126d253d95f463d3776

diff --git a/config b/config
--- a/config
+++ b/config
@@ -792,6 +792,51 @@ echo " "
 echo "32 bit compilation can use 'gfortran' under 10.5, or 'g77' under any."
 echo -n "Please enter your choice 'g77' or 'gfortran': "
 set GMS_FORTRAN=$<
+switch ($GMS_FORTRAN)
+   case g77:
+      echo "g77 does not support unit numbers higher than 99,"
+      echo "    so runtyp=tdhfx jobs will fail"
+      echo "g77 does not support quadruple precision,"
+      echo "    so heavy element DK3 resolution of the identity will fail"
+      echo "but everything else should work."
+      breaksw
+   case gfortran:
+      echo "Please type 'gfortran -dumpversion' or else 'gfortran -v' to"
+      echo "detect the version number of your gfortran."
+      echo "This reply should be a string with at least two decimal points,"
+      echo "such as 4.1.2 or 4.6.1, or maybe even 4.4.2-12."
+      echo "The reply may be labeled as a 'gcc' version,"
+      echo "but it is really your gfortran version."
+      echo -n "Please enter only the first decimal place, such as 4.1 or 4.6: "
+      echo " "
+      set GMS_GFORTRAN_VERNO=$<
+      #
+      switch ($GMS_GFORTRAN_VERNO)
+         case 4.1:
+         case 4.2:
+         case 4.3:
+         case 4.4:
+         case 4.5:
+            echo "   Alas, your version of gfortran does not support REAL*16,"
+            echo "   so relativistic integrals cannot use quadruple precision."
+            echo "   Other than this, everything will work properly."
+            breaksw
+         case 4.6:
+         case 4.7:
+            echo "   Good, the newest gfortran can compile REAL*16 data type."
+            breaksw
+         default:
+            echo "The gfortran version number is not recognized."
+            echo "It should only have one decimal place, such as 4.x"
+            exit 4
+            breaksw
+      endsw
+      breaksw
+   default:
+      echo "mac32 supports only gfortran/g77"
+      exit 4
+      breaksw
+endsw
 echo " "
 echo "This target will use the vecLib framework math library, standard in OS X."
 echo "If your OS X is 10.5 or higher, consider switching to the 'mac64' target."
