fix Lion execution, all q.p. for gfortran 4.6
qrel.src and qeigen.src modified to ensure 16-byte alignment
within the dynamic memory pool.
Lion computers set to simplistic blas.src for math library,
since its vecLib seems to be broken.
miscellaneous script changes to support these two.

Change-Id: I5294b46f0f2ed7785ae14f8751367243d5d6f7ce

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,6 +1,6 @@
 #!/bin/csh
 #
-#   26 May 2011 - configuration script to set up GAMESS' compile/link
+#   22 Nov 2011 - configuration script to set up GAMESS' compile/link
 #
 #   1. This script asks questions about FORTRAN, math libraries, and
 #   message passing libraries.  The answers to these questions are
@@ -11,10 +11,8 @@
 #   That must be attended to by hand, following comments inside it.
 #
 #            the following will always be set by this script.
-#AAD
 set GMS_VERSION=''
 set GMS_BUILD_DIR=''
-#AAD
 set GMS_TARGET=''
 set GMS_PATH=''
 set GMS_FORTRAN=''
@@ -23,8 +21,10 @@ set GMS_DDI_COMM=''
 #            the following may optionally be set to non-blank below,
 #            but will be left uninitialized in many cases.
 set GMS_MATHLIB_PATH=''
+set GMS_GFORTRAN_VERNO=''
 set GMS_IFORT_VERNO=''
 set GMS_MKL_VERNO=''
+set GMS_MAX_OSX_VERNO=''
 set GMS_SUN_OS_VERNO=''
 set GMS_SUN_FORT_VERNO=''
 set GMS_WIN_OPT=''
@@ -108,7 +108,7 @@ endif
 echo "Setting up GAMESS compile and link for GMS_TARGET=$GMS_TARGET"
 echo "GAMESS software is located at GMS_PATH=$GMS_PATH"
 echo " "
-#AAD
+#
 badbuilddir:
 echo "Please provide the name of the build locaation."
 echo "This may be the same location as the GAMESS directory."
@@ -133,12 +133,13 @@ if (! -d $GMS_BUILD_DIR/tests) then
 endif
 echo " "
 
-echo "Please provide the version name for the GAMESS executable."
+echo "Please provide a version number for the GAMESS executable."
+echo "This will be used as the middle part of the binary's name,"
+echo "for example: gamess.00.x"
 echo ""
-echo -n "Version? [00]"
+echo -n "Version? [00] "
 set GMS_VERSION=$<
 if(null$GMS_VERSION == null) set GMS_VERSION=00
-#AAD
 
 #
 #    ----- Step 2: get compiler and math library values -----
@@ -404,9 +405,36 @@ switch ($GMS_FORTRAN)
       breaksw
    case gfortran:
       echo "gfortran is very robust, so this is a wise choice."
-      echo "gfortran does not support quadruple precision,"
-      echo "         so heavy element DK3 resolution of the identity will fail"
-      echo "but everything else will work."
+      echo " "
+      echo "Please type 'gfortran -dumpversion' or else 'gfortran -v' to"
+      echo "detect the version number of your gfortran."
+      echo "This reply should be a string with at least two decimal points,"
+      echo "such as 4.1.2 or 4.6.1, or maybe even 4.4.2-12."
+      echo "The reply may be labeled as a 'gcc' version,"
+      echo "but it is really your gfortran version."
+      echo -n "Please enter only the first decimal place, such as 4.1 or 4.6: "
+      echo " "
+      set GMS_GFORTRAN_VERNO=$<
+      #
+      switch ($GMS_GFORTRAN_VERNO)
+         case 4.1:
+         case 4.2:
+         case 4.3:
+         case 4.4:
+         case 4.5:
+            echo "   Alas, your version of gfortran does not support REAL*16,"
+            echo "   so relativistic integrals cannot use quadruple precision."
+            echo "   Other than this, everything will work properly."
+            breaksw
+         case 4.6:
+            echo "   Good, the newest gfortran can compile REAL*16 data type."
+            breaksw
+         default:
+            echo "The gfortran version number is not recognized."
+            echo "It should only have one decimal place, such as 4.x"
+            exit 4
+            breaksw
+      endsw
       breaksw
    case ifort:
       #  ifort was called ifc or efc before version 8, lets ignore that now.
@@ -680,16 +708,89 @@ breaksw
 
 case mac64:
 
+tput clear
+
 echo "Compiling on Apple equipment is straightforward."
-echo "Information about installing FORTRAN can be found in the 'comp' script."
 echo " "
-echo "This target assumes the use of the GNU compiler, gfortran."
-echo "This target will use the vecLib framework math library, standard in OS X."
-echo "So, there are no further questions about FORTRAN or math libraries."
+echo "This target assumes the use of the GNU compilers, gfortran/gcc."
+echo "Information about first installing xcode from Apple, to get gcc,"
+echo "and then obtaining a precompiled gfortran for your Apple OS X version"
+echo "can be found in the 'comp' script."
 echo " "
-echo "Your OS X version must be 10.5 or higher to run GAMESS in 64 bit mode."
 set GMS_FORTRAN=gfortran
 set GMS_MATHLIB=vecLib
+#
+echo "Please type 'gfortran -dumpversion' or else 'gfortran -v' to"
+echo "detect the version number of your gfortran."
+echo "This reply should be a string with at least two decimal points,"
+echo "such as 4.1.2 or 4.6.1, or maybe even 4.4.2-12."
+echo "The reply may be labeled as a 'gcc' version,"
+echo "but it is really your gfortran version."
+echo -n "Please enter only the first decimal place, such as 4.1 or 4.6: "
+echo " "
+set GMS_GFORTRAN_VERNO=$<
+#
+switch ($GMS_GFORTRAN_VERNO)
+   case 4.1:
+   case 4.2:
+   case 4.3:
+   case 4.4:
+   case 4.5:
+      echo "   Alas, your version of gfortran does not support REAL*16,"
+      echo "   so relativistic integrals cannot use quadruple precision."
+      echo "   Other than this, everything will work properly."
+      breaksw
+   case 4.6:
+      echo "   Good, the newest gfortran can compile REAL*16 data type."
+      breaksw
+   default:
+      echo "The gfortran version number is not recognized."
+      echo "It should only have one decimal place, such as 4.x"
+      exit 4
+      breaksw
+endsw
+#
+set osxver=`/usr/bin/sw_vers -productVersion`
+set osxver=$osxver:r
+#
+switch ($osxver)
+   case 10.0:
+   case 10.1:
+   case 10.2:
+   case 10.3:
+#          10.4 was partly 64-bit, but it didn't work very well,
+#          so this is placed with the older 32 bit systems.
+   case 10.4:
+     echo "you appear to be running Mac OS X version $osxver"
+     echo "this is too old to allow 64-bit GAMESS compilation."
+     echo "Please select the 'mac32' target instead..."
+     exit
+     breaksw
+   case 10.5:
+   case 10.6:
+     echo " "
+     echo "This target will use the vecLib framework math library,"
+     echo "which is standard in OS X."
+     breaksw
+   case 10.7:
+     echo " "
+     echo "Alas, you are running Lion."
+     echo "This target will not use Apple's vecLib math library,"
+     echo "since Lion versions up to at least 10.7.2 fail to work."
+     echo "Some slow but correct FORTRAN code will be used instead,"
+     echo "with significant performance penalties for MP2/CC runs."
+     set GMS_MATHLIB='blas.o'
+     breaksw
+   default:
+     echo " "
+     echo "OS X version number is unrecognized: $osxver"
+     echo "You may experience problems, will attempt to build for Lion."
+     set osxver='10.7'
+     breaksw
+endsw
+set GMS_MAC_OSX_VERNO=$osxver
+#
+
 breaksw
 
 #       GMS_MATHLIB need be set only generically for SGI.
@@ -1308,19 +1409,25 @@ echo "#   compilation configuration for GAMESS" >> $cf
 echo "#   generated on `hostname`"              >> $cf
 echo "#   generated at `date`"                  >> $cf
 echo "setenv GMS_PATH            $GMS_PATH"           >> $cf
-echo "setenv GMS_BUILD_DIR $GMS_BUILD_DIR" >> $cf
+echo "setenv GMS_BUILD_DIR       $GMS_BUILD_DIR"      >> $cf
+#
 echo "#         machine type"                         >> $cf
 echo "setenv GMS_TARGET          $GMS_TARGET"         >> $cf
     if (null$GMS_BG_MODEL != null) \
 echo "setenv GMS_BG_MODEL        $GMS_BG_MODEL"       >> $cf
+    if (null$GMS_SUN_OS_VERNO != null) \
+echo "setenv GMS_SUN_OS_VERNO    $GMS_SUN_OS_VERNO"   >> $cf
+    if (null$GMS_MAC_OSX_VERNO != null) \
+echo "setenv GMS_MAC_OSX_VERNO   $GMS_MAC_OSX_VERNO"  >> $cf
+#
 echo "#         FORTRAN compiler setup"               >> $cf
 echo "setenv GMS_FORTRAN         $GMS_FORTRAN"        >> $cf
+    if (null$GMS_GFORTRAN_VERNO != null) \
+echo "setenv GMS_GFORTRAN_VERNO  $GMS_GFORTRAN_VERNO" >> $cf
     if (null$GMS_IFORT_VERNO != null) \
 echo "setenv GMS_IFORT_VERNO     $GMS_IFORT_VERNO"    >> $cf
     if (null$GMS_SUN_FORT_VERNO != null) \
 echo "setenv GMS_SUN_FORT_VERNO  $GMS_SUN_FORT_VERNO" >> $cf
-    if (null$GMS_SUN_OS_VERNO != null) \
-echo "setenv GMS_SUN_OS_VERNO    $GMS_SUN_OS_VERNO"   >> $cf
     if (($GMS_TARGET == win32) || ($GMS_TARGET == win64)) then
 echo "setenv GMS_WIN_OPT         $GMS_WIN_OPT"        >> $cf
 echo "setenv GMS_WIN_FLAGS       $GMS_WIN_FLAGS"      >> $cf
@@ -1350,11 +1457,12 @@ echo "setenv GMS_OFED_PATH       $GMS_OFED_PATH"      >> $cf
 echo "setenv GMS_ARMCI_PATH      $GMS_ARMCI_PATH"     >> $cf
 #
 echo " "
-echo "Your configuration for GAMESS compilation is now in $cf"
+echo "Your configuration for GAMESS compilation is now in"
+echo "     $cf"
 echo "Now, please follow the directions in"
 echo "     $GMS_PATH/misc/readme.unix"
 
-#AAD generate a Makefile in $GMS_BUILD_DIR
+#   generate a Makefile in $GMS_BUILD_DIR
 set makef=$GMS_BUILD_DIR/Makefile
 echo "GMS_PATH = $GMS_PATH" > $makef
 echo "GMS_VERSION = $GMS_VERSION" >> $makef
