Automatic LIBINT/MPQC download script
Script added: misc/getmpqc.csh  -> allows for automatic
pull, compilation of libint and mpqc.
lked updated to correctly link math libraries and libint when
the mpqc interface is turned on.

Change-Id: I685f89b6a5d86f249f92540fedc4eea1bdc399b0

diff --git a/lked b/lked
--- a/lked
+++ b/lked
@@ -76,10 +76,10 @@ set MPQC=false
 #       LDR       - the name of the loader (usually a compiler).
 #       LDOPTS    - options, such as asking for a load map.
 #       LIBRARIES - extra system libraries which must be searched.
-#       LAPACK    - default: set to 'dgeev.o dgesvd.o zheev.o'
-#                 - set to blank to take LAPACK from a math lib
 #       BLAS      - set to blas.o if not using system BLAS.
 #                   set to blank if using system BLAS.
+#       LAPACK    - default: set to 'dgeev.o dgesvd.o zheev.o'
+#                 - set to blank to take LAPACK from a math lib
 #       VECTOR    - set to vector.o on a vector processor.
 #                   set to blank on a scalar processor.
 #       QUICHE    - set to zunix.o if using true dynamic memory,
@@ -1144,19 +1144,20 @@ set STANDARD_GAMESS_OBJ3=(optcix.o ordint.o ormas1.o  \
 
 #
 #     unfortunately, the link command has become too long to show it
-#     explicitly (full command line exceeds 2048 bytes).   Show it
-#     piecemeal, taking great care that the order matches the LDR command.
+#     explicitly (full command line below will exceed 2048 bytes).
+#     Show what we will be linking piecemeal,
+#     taking great care that the order matches the actual LDR command.
 #
 echo " "
 echo The name of the linker on this machine is $LDR,
 echo and the linker options are \"$LDOPTS\".
 echo " "
-echo Object code list begins with gamess.o unport.o,
-echo followed by   BLAS code=\"$BLAS\",
-echo followed by LAPACK code=\"$LAPACK\",
-echo followed by VECTOR code=\"$VECTOR\",
-echo followed by memory code=\"$QUICHE\",
-echo followed by the standard GAMESS object code list,
+echo 'Object code list begins "gamess.o unport.o",'
+echo 'followed by   BLAS object code '\"$BLAS\",
+echo 'followed by LAPACK object code '\"$LAPACK\",
+echo 'followed by VECTOR object code '\"$VECTOR\",
+echo 'followed by memory object code '\"$QUICHE\",
+echo 'followed by the standard GAMESS object code list,'
 echo " "
 echo $STANDARD_GAMESS_OBJ1
 echo $STANDARD_GAMESS_OBJ2
@@ -1169,25 +1170,25 @@ echo "Choices for some optional plug-in codes are"
 if ($TINKER == true) then
    set QMMMOBJ="Libtad.o Libteac.o Libtedl.o Libtemo.o Libterx.o Libtfi.o"
    set QMMMOBJ="$QMMMOBJ Libtjo.o Libtpr.o Libtsx.o Tdrive.o Tinkin.o Toys.o"
-   echo "   Tinker/SIMOMM files are $QMMMOBJ"
+   echo "   Tinker/SIMOMM object files are $QMMMOBJ"
 else
    set QMMMOBJ='qmmm.o'
-   echo "   Using $QMMMOBJ, Tinker/SIMOMM code is not linked."
+   echo "   Tinker/SIMOMM code is skipped, using dummy object file $QMMMOBJ"
 endif
 #
 #   VB is turned off with vbdum.o dummy substitute in GAMESS distribution.
 if (($VB2000 == true) || ($XMVB == true)) then
    if ($VB2000 == true) then
       set VBOBJ='vb2000.o vb2gms.o'
-      echo "   Valence Bond program VB2000 files are $VBOBJ"
+      echo "   Valence Bond program VB2000 object files are $VBOBJ"
    endif
    if ($XMVB == true) then
       set VBOBJ='xmvb.o'
-      echo "   Valence Bond program XMVB files are $VBOBJ"
+      echo "   Valence Bond program XMVB object files are $VBOBJ"
    endif
 else
    set VBOBJ='vbdum.o'
-   echo "   Using $VBOBJ, neither VB program is linked."
+   echo "   Both VB programs are skipped, using dummy object file $VBOBJ"
 endif
 #
 #   NEO is turned off with neostb.o dummy substitute in GAMESS distribution.
@@ -1200,7 +1201,7 @@ if ($NEO == true) then
    echo "   Nuclear Electron Orbital code files are $NEOOBJ"
 else
    set NEOOBJ='neostb.o'
-   echo "   Using $NEOOBJ, Nuclear Electron Orbital code is not linked."
+   echo "   Nuclear Electron Orbital code skipped, using dummy object $NEOOBJ"
 endif
 #
 #    CUDA (et cetera) libraries below will require editing to match
@@ -1225,7 +1226,6 @@ else
    set GPU_LIBS=""
 endif
 #
-#
 #   MPQC is turned off with mpqcst.o dummy substitute in GAMESS distribution.
 if ($MPQC == true) then
 # Make sure MPQC and LIBINT are present in $GMS_BUILD_DIR
@@ -1246,25 +1246,23 @@ if ($MPQC == true) then
     set MPQCLIBS = "$MPQCLIBS $GMS_BUILD_DIR/mpqc/lib/$LIB_NAME"
    end
 #LIBINT libraries
-   set LIBINT = "-L$GMS_BUILD_DIR/libint-gamess/lib -lint2 -lm -ldl"
+   set LIBINT = "-L$GMS_BUILD_DIR/libint/lib -lint2 -lm -ldl"
 #LIBRARIES
    switch ($GMS_MATHLIB)
-   case mkl:
-   set LIBRARIES = "-Wl,--start-group $LIBRARIES -Wl,--end-group -lstdc++"
-       breaksw
+    case mkl:
+     set LIBRARIES = "-Wl,--start-group $LIBRARIES -Wl,--end-group -lstdc++"
+    breaksw
     case acml:
-       echo 'Build GAMESS-MPQC manually.'
-       exit 4
-       breaksw
+     set LIBRARIES="$GMS_MATHLIB_PATH/libacml.a -lm -lstdc++"
+    breaksw
     case atlas:
-       echo 'Build GAMESS-MPQC manually.'
-       exit 4
-       breaksw
+     set LIBRARIES = "$LIBRARIES  -llapack -lstdc++"
+    breaksw
     case none:
-       echo 'system math library is required'
-       exit 4
-       breaksw
-    endsw
+     echo 'system math library is required'
+     exit 4
+    breaksw
+   endsw
 # The system math libraries must contain LAPACK: remove GAMESS LAPACK
    set LAPACK=''
    set MPQCOBJ=''
@@ -1274,15 +1272,15 @@ else
    set MPQCOBJ='mpqcst.o'
    set MPQCLIBS=''
    set LIBINT=''
-   echo "   Using $MPQCOBJ, MPQC code is not linked."
+   echo "   MPQC code is skipped, using dummy object file $MPQCOBJ"
 endif
 #
 #
 echo " "
-echo "   message passing libraries are"
+echo "   The message passing libraries searched are"
 echo $MSG_LIBRARIES
 echo " "
-echo "   other libraries to be searched are"
+echo "   Other libraries, including math libraries, to be searched are"
 echo $LIBRARIES
 echo " "
 #
