Checktest implemented through Makefile.in
The scripts runtest and checktst in tests/ still work and can be used if
the tests folder is copied elsewhere.

The comments in Makefile.in describe how to add new tests to the
checktest target.   The supplied rungms script has been updated to run
without a priori knownledge of the system.  It will inherit information
from install.info to determine the paths and executable name.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -40,21 +40,28 @@ gamess : $(GAMESS)
 $(GAMESS) : $(DDI_LIB) $(OBJ) $(OBJ_AUX) $(OBJ_DIR)/zunix.o
 	@$(LINK) $(EXE) $(GMS_VERSION) >/dev/null
 
-#Compile any module (can I make "make $(module)" work?)
+#Compile any module (I can't quite do "make $(module)" yet)
 $(OBJ_DIR)/%.o :$(ACTVTE) $(SRC_DIR)/%.src 
 	@if [ -e $(OBJ_DIR)/$(notdir $(basename $@)).f ]; then rm $(OBJ_DIR)/$(notdir $(basename $@)).f;fi
 	@$(COMP) $(notdir $(basename $@)) 2>&1 1>/dev/null | sed -e $(SEDSRC)
+modules : $(OBJ)
+
+#I like to keep the activated source in the OBJ_DIR for use with FTNCHEK
 $(OBJ_DIR)/%.f :$(ACTVTE) $(SRC_DIR)/%.src
 	@if [ -e $(OBJ_DIR)/$(notdir $(basename $@)).f ]; then rm $(OBJ_DIR)/$(notdir $(basename $@)).f;fi
 	@$(COMP) $(notdir $(basename $@)) true
 $(OBJ_DIR)/%.lis :$(ACTVTE) $(SRC_DIR)/%.src $(OBJ_DIR)/%.f
 	$(FTNCHEK) $(FTNCHEK_OPT) $(OBJ_DIR)/$(notdir $(basename $@)).f 2>&1 | sed -e $(SEDSRC2) > $@
-modules : $(OBJ)
 $(ACTVTE) :
 	 Compilation of $(ACTVTE) requires running $(GMS_PATH)/config
+
+#zunix is always required
 $(OBJ_DIR)/zunix.o : $(SRC_DIR)/zunix.c
 	@$(COMPALL) 1 2>&1 1>/dev/null
 
+#compall is parsed to determine which MODULES are to be compiled.
+#These extra files may be necessary and LKED will determine that so
+#I think it is best just to make sure they are compiled anyway.
 $(OBJ_DIR)/blaswrap.o : $(GMS_PATH)/misc/blaswrap.src
 	@if [ -e $(OBJ_DIR)/blaswrap.f ]; then rm $(OBJ_DIR)/blaswrap.f;fi
 	@$(COMP) blaswrap 2>&1 1>/dev/null | sed -e $(SEDSRC)
@@ -66,6 +73,8 @@ $(OBJ_DIR)/vector.o : $(SRC_DIR)/vector.src
 	@$(COMP) vector 2>&1 1>/dev/null | sed -e $(SEDSRC)
 
 
+#I don't yet try to micro manage DDI compilation.
+#Compilation is very quick anyway.
 ddi : $(DDI_LIB) $(DDIKICK)
 $(DDI_LIB) $(DDIKICK) :
 	$(GMS_PATH)/ddi/compddi
@@ -74,14 +83,26 @@ $(DDI_LIB) $(DDIKICK) :
 	@if [ -e $(GMS_PATH)/ddi/data_server.x ]; then mv $(GMS_PATH)/ddi/data_server.x $(DATASERVER);fi
 	@if [ -e $(GMS_PATH)/ddi/libddi.a ] && [ "$(GMS_PATH)/ddi/libddi.a" != "$(DDI_LIB)" ]; then mv $(GMS_PATH)/ddi/libddi.a  $(DDI_LIB);fi
 
-tags : $(SRC_DIR)/*.src
-	$(CTAGS) --langmap=fortran:.src $(SRC_DIR)/* $(GMS_PATH)/ddi/src/*
 
+#### Auxillary targets ####
+
+#at runtime, extra flags can be added (like -e to make emacs compitable tags)
+tags : $(SRC_DIR)/*.src
+	$(CTAGS) $(CTAGS_FLAGS) --langmap=fortran:.src $(SRC_DIR)/* $(GMS_PATH)/ddi/src/*
+
+#FTNCHEK: a summary is printed to STDOUT along with the gamess.lis and individual lis files in OBJ_DIR
 gamess.lis : $(ACT) $(LIS)
 	$(FTNCHEK) $(FTNCHEK_OPT2) $(ACT) 2>&1 | sed -e $(SEDSRC2) > gamess.lis
 check : gamess.lis
 	@awk '{if($$0 ~ "[1-9]+ syntax errors") print "------\n",$$0,"\n------"}' gamess.lis
 	@awk '{if($$0 ~ "[1-9]+ warning[s]* issued") print $$0}' gamess.lis
+
+#Build a tarball based on a git commit or tag
+COMMIT=HEAD
+TAR_VERSION=$(GMS_VERSION)
+dist :
+	@echo "Creating $(GMS_BUILD_PATH)/gamess-$(TAR_VERSION).tar.gz for commit $(COMMIT) in branch `git name-rev --name-only $(COMMIT)`"
+	@cd $(GMS_PATH) && git archive --format=tar --prefix=gamess-$(TAR_VERSION)/ $(COMMIT) | gzip >$(GMS_BUILD_PATH)/gamess-$(TAR_VERSION).tar.gz
 
 clean :
 	rm -rf $(OBJ)
@@ -95,3 +116,90 @@ clean_ddi :
 	rm -rf $(DDIKICK)
 	rm -rf $(DDITEST)
 	rm -rf $(DATASERVER)
+
+
+
+
+############ The new CHECKTEST ##################
+# The target checktest will run the exam inputs and perform the error checking.
+# If an examXX.log file exists, it will not be rerun and only checked.  If the
+# user wishes to only a few of the exams:
+#
+# make checktest EXAMS=exam05
+# make checktest EXAMS="exam05 exam30"
+# 
+# To add new exam, two files are required
+#
+# The input
+#    $(GMS_PATH)/tests/mytest.inp
+# The script (use already present examXX scripts as templates)
+#    $(GMS_PATH)/tests/scripts/mytest
+#
+# The new exam can be run and tested by itself
+#    make checktest EXAMS=mytest
+#
+#
+
+RUNGMS=$(GMS_PATH)/rungms
+
+GMS_EXT = log
+
+EXAMS = exam01 exam02 exam03 exam04 exam05 exam06 exam07 exam08 exam09 exam10 exam11 exam12 exam13 exam14 exam15 exam16 exam17 exam18 exam19 exam20 exam21 exam22 exam23 exam24 exam25 exam26 exam27 exam28 exam29 exam30 exam31 exam32 exam33 exam34 exam35 exam36 exam37 exam38 exam39 exam40 exam41 exam42 exam43 exam44
+
+EXAM_INPUTS = $(patsubst %,$(GMS_PATH)/tests/%.inp,$(EXAMS))
+
+EXAM_OUTPUT_DIR = $(GMS_BUILD_PATH)/tests
+EXAM_LOG = $(patsubst %,$(EXAM_OUTPUT_DIR)/%.$(GMS_EXT),$(EXAMS))
+EXAM_RST = $(patsubst %,$(EXAM_OUTPUT_DIR)/%.rst,$(EXAMS))
+EXAM_DAT = $(patsubst %,$(EXAM_OUTPUT_DIR)/%.dat,$(EXAMS))
+EXAM_TRJ = $(patsubst %,$(EXAM_OUTPUT_DIR)/%.trj,$(EXAMS))
+#this is a dummy that is never actually created but helps make the checktest target
+EXAM_CHK = $(patsubst %,$(EXAM_OUTPUT_DIR)/%.chk,$(EXAMS))
+
+$(EXAM_OUTPUT_DIR)/%.$(GMS_EXT) : $(GAMESS) $(GMS_PATH)/tests/%.inp
+	@cd $(EXAM_OUTPUT_DIR) && if [ -e $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).dat ]; then rm $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).dat;fi
+	@cd $(EXAM_OUTPUT_DIR) && if [ -e $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).rst ]; then rm $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).rst;fi
+	@cd $(EXAM_OUTPUT_DIR) && if [ -e $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).trj ]; then rm $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).trj;fi
+	@cd $(EXAM_OUTPUT_DIR) && if [ -e $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).$(GMS_EXT) ]; then rm $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).$(GMS_EXT);fi
+	cd $(EXAM_OUTPUT_DIR) && $(RUNGMS) $(notdir $(basename $@)) $(GMS_VERSION) > $(notdir $(basename $@)).$(GMS_EXT) 2>&1
+
+exams : $(EXAM_LOG)
+
+
+#These environment variables are required to run the 
+# the checking scripts in $(GMS_PATH)/tests/scripts
+#Tolerances can be changed on the command line
+#  make checktest tolE=6e-5
+export tolC=0.3
+export tolD=0.0001
+export tolE=0.00000001
+export tolG=0.00001
+export tolH=0.0001
+export tolI=0.0001
+export tolL=0.1
+export tolO=0.0001
+export tolP=0.0001
+export tolR=0.0001
+export tolS=0.01
+export tolT=0.000001
+export tolV=0.00000001
+export tolW=0.1
+export tolX=0.00001
+export chkabs=$(GMS_PATH)/tests/scripts/chkabs
+
+CHK_PATH=$(GMS_PATH)/tests/scripts
+
+#print the restuls of the examXX script
+CHK_AWK = -v exam=$(notdir $(basename $@)) '{ printf "%-10s %-63s",exam,$$0 }';if [ $$? != 0 ]; then echo "!!Failed";else echo Passed;fi 
+#determine that the exam finished
+GREP_TERM = grep -q "TERMINATED NORMALLY" $(EXAM_OUTPUT_DIR)/$(notdir $(basename $@)).$(GMS_EXT);if [ $$? != 0 ]; then echo "$(notdir $(basename $@))     !!! TERMINATED ABNORMALLY !!!";exit;fi
+
+#check in single exam
+$(EXAM_OUTPUT_DIR)/%.chk : $(EXAM_OUTPUT_DIR)/%.$(GMS_EXT)
+	@cd $(EXAM_OUTPUT_DIR) && $(GREP_TERM) && $(CHK_PATH)/$(notdir $(basename $@)) $(notdir $(basename $@)).$(GMS_EXT) | awk $(CHK_AWK)
+	
+#since .chk files are never created make will always check all entries in EXAMS.
+checktest : $(EXAM_LOG) $(EXAM_CHK)
+
+clean_exams :
+	rm -rf $(EXAM_RST) $(EXAM_DAT) $(EXAM_LOG) $(EXAM_TRJ)
