LIBCCHEM interfacing
Previous LIBCCHEM required ifort/MKL/iMPI and CUDA 4.1 on Fermi boards.
This is generalized:
  success using gfortran in addition to ifort
  success using Atlas in addition to MKL
  partial success using MVAPICH2 in addition to iMPI
  partial success using CUDA 5.0 in addition to CUDA 4.1
  older Tesla and newer Kepler boards shown to work.

unresolved #1:
CUDA 5.0 build for Tesla will crash in initial SCF iteration, with:
         terminate called after throwing an instance of 'cuda::error'
         what(): rysq/src/cuda/kernel/quadrature2.hpp:386: invalid argument
CUDA 5.0 build for Fermi will get slightly wrong SCF energies,
         so it is unknown if the MP2 and CCSD(T) kernels work.
         It is entirely possible that the problem is same as Tesla,
         but could also be in nvcc or 304.64 device driver.
CUDA 5.0 build for Fermi or for Kepler runs correctly on Kepler.

The last two are reproducible by Carl Ponder on NVidia's test platform.
Considerable effort was put into compiler flags and synching 5.0 software,
without any luck.

unresolved #2:
I don't know how to use the new MVAPICH2 on the Mellanox boards in 'dynamo'
to run multinode: therefore all Tesla testing was done on a single node.
This is a very minor point!

Change-Id: Ie5b6a194864c6f80b5fef0c3f8c301a27aaf4b1a

diff --git a/tools/gms b/tools/gms
--- a/tools/gms
+++ b/tools/gms
@@ -1,20 +1,22 @@
 #!/bin/csh
 #
-#    2 May 2012:    This front-end 'gms' script runs interactively,
+#   4 Feb 2013:    This front-end 'gms' script runs interactively,
 #   to send the back-end 'rungms' GAMESS job to a batch schedular,
 #   namely Sun Grid Engine (SGE) -or- Portable Batch System (PBS)
 #
-#   The clusters which use this 'gms' utilize iMPI for their Infiniband,
-#   but differ in the schedular.  To use this, edit the back-end "rungms"
-#   script (provided with the source code version of GAMESS) to use MPI,
-#            set TARGET=mpi
-#   Additional customizations for each specific cluster are given below.
-#   Like this front-end, the MPI part of the back-end contains logic
-#   to support either SGE or PBS.
+#   Three of our clusters use this 'gms' front-end:
+#        dynamo   = SGE, 8-core nodes, most with old Tesla GPUs
+#        chemphys = PBS, 6 core nodes, no GPUs
+#        exalted  = SGE, 6 core nodes, many Fermi GPUs, one Kepler GPU
+#   All of them use Infiniband.  That means that the 'rungms' back-end
+#   is either using execution target 'mpi' to run GAMESS, or execution
+#   target 'ga' to run GAMESS+LIBCCHEM on the GPUs.  The mpi/ga parts
+#   of 'rungms' contain SGE and PBS portions, to detect the nodes that
+#   are assigned to each particular job.
 #
-#   This 'gms' certainly can't be used elsewhere without customization,
-#   so anyone encountering the 'default' below has to work their way
-#   through this script, and also any 'rungms' consequences.
+#   This 'gms' and the 'rungms' which it submits certainly can't be used
+#   elsewhere without customization, but if you know your own hardware
+#   and batch queue rules, you can certainly get this to work for you.
 #
 #
 #    ===== next section sets a few cluster-specific data
@@ -25,35 +27,44 @@
 #    except some of these clusters have GPUs present, non-uniformly.
 #
 switch (`hostname`)
-#       necessary 'rungms' customizations:
-#           change the iMPI version number to 3.2.1,
-#           execute by '3steps',
-#       about 2/3 of the nodes have old GPU pairs, but they are turned off.
    case dynamo.iprt.iastate.edu:
+#                  necessary 'rungms' customizations for ISU:
+#           change both mpi/ga parts!!!
+#           change execution target to mpi
+#           change the ifort version number to 10.1.018
+#           change the MKL   version number to 10.0.3.020
+#           change the iMPI  version number to 3.2
+#           change execution to '3steps' since it is very old iMPI.
+#           about 2/3 of the nodes have a pair of old Tesla GPUs.
       set SCHED=SGE
       set CLUSTER=dynamo
       set PPN_MAX=8
+      set NUMGPU=0
       breaksw
-#       necessary 'rungms' customizations:
-#           change the iMPI version number to 4.0.1.007,
-#           execute by 'hydra',
-#           ignore CUDA stuff.
-#       there are no GPUs in this cluster.
    case chemphys2011.fi.ameslab.gov:
+#                  necessary 'rungms' customizations for ISU:
+#           change the mpi part only!!!
+#           change the ifort version number to composerxe-2011.1.107
+#           change the MKL   version number to composerxe-2011.1.107
+#           change the iMPI  version number to 4.0.1.007
+#           there are no GPUs in this cluster.
       set SCHED=PBS
       set CLUSTER=chemphys
       set PPN_MAX=6
+      set NUMGPU=0
       breaksw
-#       necessary 'rungms' customizations:
-#           change the iMPI version number to 4.0.2.003,
-#           change the pathname to CUDA runtime files.
-#           execute by GA using '3-steps' only,
-#           launch only 1 process per node, even though its hex-cores.
-#       all nodes have at least a GPU pair, about 1/3 have four GPUs
    case exalted.iprt.iastate.edu:
+#                  necessary 'rungms' customizations for ISU:
+#           change both mpi/ga parts!!!
+#           change the ifort version number to composerxe-2011.4.191
+#           change the MKL   version number to composerxe-2011.4.191
+#           change the iMPI  version number to 4.0.2.003
+#           all nodes have at least a GPU pair, about 1/3 have four GPUs
+#           official policy is to require the use of the GPUs!
       set SCHED=SGE
       set CLUSTER=exalted
-      set PPN_MAX=1
+      set PPN_MAX=6
+      set NUMGPU=2
       breaksw
    default:
       echo "This cluster is unrecognized, please customize for your site."
@@ -114,14 +125,33 @@ while ($#argv > 0)
         breaksw
       case -test:
         set TESTJOB=true
-        if ($CLUSTER != dynamo) then
-           echo "Ignoring -test option, there is no test queue on this cluster"
-           set TESTJOB=false
-        endif
+        switch ($CLUSTER)
+           case dynamo:
+              echo "Test job will run in the four node 'reserved' queue."
+              breaksw
+           case exalted:
+              echo "Test job will run in the two node 'dev' queue."
+              breaksw
+           default:
+              echo "Ignoring -test, there is no test queue on this cluster"
+              set TESTJOB=false
+              breaksw
+        endsw
+        breaksw
+#            a way to get at an 'exalted' node with one Kepler board.
+      case -kepler:
+        set KEPLER=true
+        set TESTJOB=true
+        set NUMGPU=1
+        echo "Test job will run in the one node 'experimental' queue."
         breaksw
 #            in case the schedular lets us request nodes with GPUs...
       case -gpu:
         set NUMGPU=$argv[1]
+        shift
+        breaksw
+      case -ccmem:
+        set CCMEM=$argv[1]
         shift
         breaksw
 #            next two specify GAMESS binary's "version number" and pathname
@@ -164,16 +194,22 @@ while ($#argv > 0)
    endsw
 end
 #
+#     Global Arrays usage by GAMESS+LIBCCHEM requires running one MPI
+#     process per node: parallelism inside node is always by threads.
+if ($NUMGPU > 0) set PPN_MAX=1
+#
 if ($?JOB == 0)     set JOB=help
-if ($?VERNO == 0)   set VERNO=129
+if ($?VERNO == 0)   set VERNO=130
 if ($?LOGFILE == 0) set LOGFILE=default
 if ($?XPATH == 0)   set XPATH=none
 if ($?NCPUS == 0)   set NCPUS=0
 if ($?WALL == 0)    set WALL=default
 if ($?HOG == 0)     set HOG=false
 if ($?TESTJOB == 0) set TESTJOB=false
-if ($?PPN == 0)     set PPN=$PPN_MAX
+if ($?KEPLER == 0)  set KEPLER=false
 if ($?NUMGPU == 0)  set NUMGPU=0
+if ($?CCMEM == 0)   set CCMEM=0
+if ($?PPN == 0)     set PPN=$PPN_MAX
 if ($?EXTBAS == 0)  set EXTBAS=/dev/null
 if ($?SAVE30 == 0)  set SAVE30=false
 if ($?SAVE37 == 0)  set SAVE37=false
@@ -191,13 +227,11 @@ if ($JOB == help) then
    echo "             of cores per node in this cluster ($PPN_MAX), then"
    echo "             X will be rounded downward to a multiple of $PPN_MAX,"
    echo "             or rounded to a multiple of Y, if -ppn is selected."
-   echo "   -hog      reserves one (1) entire node for this run, so you may"
-   echo "             choose -p from 1 to $PPN_MAX, but be assured that the"
-   echo "             entire memory of the node can be used by your run."
-   echo "   -ppn Y    reserve more than one whole node for this run, running"
-   echo "             Y compute processes in each node.  Of course, Y should"
-   echo "             not exceed this cluster's core/node count, $PPN_MAX."
-   echo "                  Note: -hog and -ppn are mutually exclusive."
+   #### "   -hog      reserves one (1) entire node for this run, so you may"
+   #### "             choose -p from 1 to $PPN_MAX, but be assured that the"
+   #### "             entire memory of the node can be used by your run."
+   echo "   -ppn Y    run only Y compute processes in each node.  Of course,"
+   echo "             Y cannot exceed this cluster's core/node count, $PPN_MAX."
    echo "   -w        wall clock time, as dd:hh:mm:ss (default=12:00:00=12 hrs)"
    echo " "
    echo "Other options, including GPU flags, can be displayed by 'gms -help'."
@@ -228,32 +262,40 @@ if ($JOB == morehelp) then
    echo " "
  switch ($CLUSTER)
  case dynamo:
-   #-echo "   -gpu n   requests nodes with GPUs be allocated,"
-   #-echo "            at most, 2 Tesla T10 GPUs can be requested."
-   #-echo "            Only 26 of the 34 production nodes have GPUs installed."
-   #-echo "            The default is n=0, to run the non-GPU linked binary."
-   echo "   -test    executes in a 4-node "reserved" programming queue."
-   echo "            the -test option is incompatible with -hog/-ppn."
+   echo "   -gpu n   requests nodes with GPUs be allocated,"
+   echo "            at most, 2 Tesla T10 GPUs can be requested."
+   echo "            Only 26 of the 34 production nodes have GPUs installed."
+   echo "            The default is n=0, to run the non-GPU linked binary."
+   echo "   -ccmem M core's memory limit (default M=8g). Include m/g units!"
+   echo "   -test    executes in a 4-node 'reserved' programming queue."
    echo " "
+   echo "      NOTE: the standard -p flag counts in units of nodes,"
+   echo "            not cores, if the job is running on GPUs."
    breaksw
-#            nodes with 4 GPUs are -0, -1, -3, -5, -6, -16, -17, -24.
  case exalted:
    echo "   -gpu n   requests nodes with n=2 or n=4 GPUs be allocated,"
    echo "            the GPUs are Fermi C2070s, 5.25 GBytes ECC memory each."
    echo "            Only 8 of 25 nodes have 4 GPUs, the rest have 2 GPUs,"
    echo "            so it is easier to schedule 2 GPUs."
    echo "            The default is n=2, and there is no non-GPU binary."
+   echo "   -ccmem M core's memory limit (default M=6g). Include m/g units!"
+   echo "   -test    executes in a 2-node 'dev'          programming queue."
+   echo "   -kepler  executes in a 1-node 'experimental' programming queue,"
+   echo "            which contains a single Kepler GPU."
+   echo " "
+   echo "      NOTE: the standard -p flag counts in units of nodes,"
+   echo "            not cores, if the job is running on GPUs."
    breaksw
  case chemphys:
    breaksw
  endsw
-   echo "Basic flags can be displayed by typing just 'gms'."
-   echo "This cluster's hardware can be displayed by 'gms -cluster'."
-   exit
+ echo "Basic flags can be displayed by typing just 'gms'."
+ echo "This cluster's hardware can be displayed by 'gms -cluster'."
+ exit
 endif
 #
 if ($JOB == cluster_config) then
-   tput clear
+ tput clear
  switch ($CLUSTER)
  case dynamo:
    echo "The head node of this cluster is named dynamo.iprt.iastate.edu,"
@@ -277,7 +319,7 @@ if ($JOB == cluster_config) then
    echo "The 31 remaining production nodes (compute-0-4 to -0-34) thus are"
    echo "divided into 22 nodes with GPU pairs, and 9 nodes that lack them."
    echo " "
-   echo "The network in this cluster is an Infiniband, 4X DDR quality,"
+   echo "The network in this cluster is an Mellanox Infiniband, 4X DDR quality,"
    echo "offering 16 Gbit/sec unidirectional bandwidth.  Of course, there"
    echo "is also a gigabit ethernet for ordinary system management."
    echo " "
@@ -299,7 +341,7 @@ if ($JOB == cluster_config) then
    echo "The GPUs are Nvidia Fermi C2070 type,"
    echo "each GPU has 5.25 GByte ECC-enabled memory."
    echo " "
-   echo "The network in this cluster is an Infiniband, 4X QDR quality,"
+   echo "The network in this cluster is an Qlogic Infiniband, 4X QDR quality,"
    echo "offering 32 Gbit/sec unidirectional bandwidth.  Of course, there"
    echo "is also a gigabit ethernet for ordinary system management."
    echo " "
@@ -325,12 +367,16 @@ if ($JOB == cluster_config) then
    echo "     900 GBytes of /scratch disk (two striped 3 Gbps SATA disks),"
    echo "     connected by 4X QDR Infiniband (32 Gbps bandwidth)."
    echo " "
+   echo "The network in this cluster is an Mellanox Infiniband, 4X QDR quality,"
+   echo "offering 32 Gbit/sec unidirectional bandwidth.  Of course, there"
+   echo "is also a gigabit ethernet for ordinary system management."
+   echo " "
    echo "This cluster is based on Rocks/Linux, with the PBS batch schedular,"
    echo "and all the usual software: gfortran/ifort, MKL, various MPIs..."
    echo " "
    breaksw
  endsw
-   exit
+ exit
 endif
 #
 #    ===== next section tests existence of various files
@@ -424,10 +470,14 @@ if ($PPN > $PPN_MAX) then
    exit
 endif
 #
+#        'hog' is a non-functional concept below, we are no longer
+#        trying to share nodes for multiple serial jobs,
+#        as it just fragments the cluster.
 if ($NCPUS < $PPN) then
    set NNODES=1
-   set WHOLENODE=false
-   if ($HOG == true) set WHOLENODE=true
+   #--set WHOLENODE=false
+   #--if ($HOG == true) set WHOLENODE=true
+   set WHOLENODE=true
 else
 #     jobs running more than one node come here, to ensure the
 #     the core count is rounded down to multiple of PPN.
@@ -487,21 +537,33 @@ if ($SCHED == PBS) then
    if ($WHOLENODE == true) set PBS_RESOURCES=":ppn=$PPN"
 endif
 #
-#   SGE's 'exclusive' resource causes entire nodes be reserved,
-#   and it changes the units of the -pe option to be 'nodes',
-#   rather than 'cores'.  At this point, the variable NNODES is
-#   equal to NCPUS only if the job is not reserving whole nodes.
-#   Since we use 'mpd' process initiation, we have to guarantee
-#   any one user doesn't overlap, hence "wholenode" is just turned on.
+#   at least at our site, SGE is set to reserve entire nodes, in part
+#   this requires passing a node count to the -pe prolog/epilog scripts.
 #
-#   the 'reserved' resource allocates from four nodes that
-#   are dedicated to programming use only, at our particular site.
 if ($SCHED == SGE) then
-   if ($TESTJOB == true) then
-      set SGE_RESOURCES="$SGE_RESOURCES -l reserved"
+   set WHOLENODE=true
+   if ($TESTJOB == false) then
+#
+#          at ISU, the 'exclusive' queue is for production runs.
+#          As the name suggests, this queue allocates entire nodes to
+#          a batch job, so all cores/GPUs/RAM/disk belong to this job.
+      set SGE_RESOURCES="$SGE_RESOURCES -l exclusive -q exclusive.q"
    else
-      set WHOLENODE=true
-      if ($WHOLENODE == true) set SGE_RESOURCES="$SGE_RESOURCES -l exclusive -q exclusive.q"
+#
+#          at ISU, reserved, dev, or experimental resource allocates nodes
+#          from batch queues by those specific names.  These are queues at
+#          our specific site which are dedicated to runs which may explore
+#          new GPUs, experimental software, or just new GAMESS code.
+      if ($CLUSTER == dynamo) then
+         set SGE_RESOURCES="$SGE_RESOURCES -l reserved"
+      endif
+      if ($CLUSTER == exalted) then
+         if ($KEPLER == false) then
+            set SGE_RESOURCES="$SGE_RESOURCES -q dev"
+         else
+            set SGE_RESOURCES="$SGE_RESOURCES -q experimental"
+         endif
+      endif
    endif
    if ($NCPUS < $PPN) set PPN=$NCPUS
    set SGE_RESOURCES="$SGE_RESOURCES -l h_rt=$seconds"
@@ -529,9 +591,11 @@ if ($CLUSTER == dynamo) then
 endif
 #
 #    Some clusters may have graphical processing units on some nodes.
-#    One     of ISU's clusters has some nodes with 0, and some with 2 GPUs
-#    Another of ISU's clusters has some nodes with 2, and some with 4 GPUs,
-#            and it the cluster's policy that GPUs are always to be used.
+#    ISU's  dynamo cluster has some nodes with 0, and some with 2 GPUs,
+#                  most runs are non-GPU using mpi target,
+#                  but GAMESS+LIBCCHEM can be used if user's wish.
+#    ISU's exalted cluster has some nodes with 2, and some with 4 GPUs,
+#                  and it is policy that GPUs are -always- to be used.
 #    the GPU-possessing nodes are set up as a consumable resource in SGE.
 #    we keep GAMESS linked to two binaries:
 #         gamess.$VERNO.x or if LIBCHEM added, as gamess.cchem.$VERNO.x
@@ -540,27 +604,26 @@ switch ($CLUSTER)
    case chemphys2011:
       if ($NUMGPU > 0) then
          echo Ignoring GPU request, this cluster has no GPUs.
-         NUMGPU=0
+         set NUMGPU=0
       endif
       breaksw
    case dynamo:
       if ($NUMGPU > 2) set NUMGPU=2
       set SGE_RESOURCES="$SGE_RESOURCES -l gpu=$NUMGPU"
+      if ($CCMEM == 0) set CCMEM=8g
       breaksw
    case exalted:
-#         dedicated GPU cluster should always hardwires GPU request
-#         a backdoor exists, just in case we need to test CPU-only binary,
-#         by entering a negative number for the GPU count.
-#         NUMGPU is passed to run-time script below, as the actual
-#         number of GPUs requested, while the schedular needs to be
-#         told 2 or 4, which are the two resource catagories.
+#         This dedicated GPU cluster always hardwires non-zero GPU request!
+#            A backdoor exists, just in case we want to test a pure GAMESS
+#            binary, by entering a negative number for the GPU count.
+#         Schedular needs to be told 2 or 4 as the GPU count, since
+#         our SGE is configured to have those two resource catagories.
+#         Thus a request for 2 GPUs might end up on a node with 4,
+#         but a request for 4 should end up only on those with 4.
       if ($NUMGPU >= 0) then
-         if ($NUMGPU == 0) set NUMGPU=2
          if ($NUMGPU > 4)  set NUMGPU=4
-         if ($NUMGPU == 1) set GPURESOURCE=1
-         if ($NUMGPU == 2) set GPURESOURCE=2
-         if ($NUMGPU == 3) set GPURESOURCE=3
-         if ($NUMGPU == 4) set GPURESOURCE=4
+         if ($NUMGPU >= 1) set GPURESOURCE=2
+         if ($NUMGPU >= 3) set GPURESOURCE=4
          set SGE_RESOURCES="$SGE_RESOURCES -l gpu=$GPURESOURCE"
       endif
       breaksw
@@ -578,10 +641,21 @@ if ($XPATH != none) then
    mv ~/scr/$JOB.mung ~/scr/$JOB.script
 endif
 #
-#    special option to hack in the desired GPU count
+#    special option to hack in the desired GPU count,
+#    and force execution by the Global Array section of 'rungms'.
 #
 if ($NUMGPU > 0) then
    sed -e /NUMGPU=0/s//NUMGPU=$NUMGPU/ \
+       -e /TARGET=mpi/s//TARGET=ga/ \
+      ~/scr/$JOB.script > ~/scr/$JOB.mung
+   mv ~/scr/$JOB.mung ~/scr/$JOB.script
+endif
+#
+#    special option to hack in the desired node memory for LIBCCHEM,
+#    this option is irrelevant to a normal GAMESS binary.
+#
+if ($CCMEM != 0) then
+   sed -e /memory=6g/s//memory=$CCMEM/ \
       ~/scr/$JOB.script > ~/scr/$JOB.mung
    mv ~/scr/$JOB.mung ~/scr/$JOB.script
 endif
